#
# configuration
#

# name of the site
name: Nico Müller

# description of the site
description: Softwareentwickler

# avatar
avatar:

# footer-links
footer-links:
  github enm1989
  twitter: enm1989
