# Site settings
title: DevCore
email: nico.mueller.1989@googlemail.com
description: "Die Gedanken eines Entwicklers in Schriftform."
baseurl: ""
twitter_username: ENM1989
github_username:  ENM1989

# Build settings
markdown: kramdown
permalink: pretty
